language: python
python:
  - "2.7"

language: r
r: bioc-release
cache: packages

# command to install dependencies
install: 
 - pip install -r requirements.txt
 - python setup.py install

# command to run tests
script:
 - slamdunk -h 
 - test_sample.sh
 - slamdunk/test/test_sample.sh
 - pytest

