sudo: required

language: python
python:
  - "2.7"
  - "3.5"

cache: pip
cache: apt   
cache:
    directories:
        - /home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/slamdunk/plot/Rslamdunk
addons:
    apt:
        packages:
            - r-base

# command to install dependencies
install: 
 - pip install -r requirements.txt
 - python setup.py -q install

# command to run tests
script:
 - slamdunk -h
 - slamdunk/test/test_sample.sh
 - pytest

